# This file was generated by GoReleaser. DO NOT EDIT.
cask "lk" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "b7a1c72d18319fa4ce051091e60ac1488d2708acfdb3261df67aaad001f44b05"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c41464ea2ce037620fbfd24f9266aab93d14f59e93b3653cabc185f5793ab7e9"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1999ad0071187dc88e47990ca1d67d64c5c96200f4a504f22ca0af67d6833763"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00c4dea9db77028d12a5080b309f210b849fd44b2aac74ee9bce37ca82b2148f"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lk"
  desc "Linkana CLI — parametrização programática de buyers"
  homepage "https://github.com/linkanalabs/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lk"]
    end
  end

  # No zap stanza required

end
