# This file was generated by GoReleaser. DO NOT EDIT.
cask "lk" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "b4b9209dc972ed39784ef1dcfb2850788d0a085fadc546f690f84c7cd6f69ce1"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4754c891256ad28903b32966c7816527b6c24dca1ae29c62d06c17f360001177"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d3b6a5ad98bd715cf7b8438f5bc687d98235df6446cac1058fd03a053d7ecfe"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "af3a81d014f6d25318ff3e2db27ab631e8f92b26213c872f2cc669e0a06bf527"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lk"
  desc "Linkana CLI — parametrização programática de buyers"
  homepage "https://github.com/linkanalabs/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lk"]
    end
  end

  # No zap stanza required

end
