# This file was generated by GoReleaser. DO NOT EDIT.
cask "lk" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "1f20d13ed40c5347ac7c54bbafbffa2efc6999125eaddb5c1633f31916dfc446"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ceb822f69e1ec5918de2607dd44c3d4766b8756d97074e055de492f84b45f8aa"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5a55ab0d1244129fe3cf872322f3cb6d7797f88dfdac12572b21c94ddb4a2f96"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1002ca4374ca01e4ac6c6c9d18990add82c75dc1716b314c575ab13829999404"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lk"
  desc "Linkana CLI — parametrização programática de buyers"
  homepage "https://github.com/linkanalabs/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lk"]
    end
  end

  # No zap stanza required

end
